# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'tucfa.ca'
tagline:          'Faculty Association of Tyndale University College, Toronto'
description:      'Official website of the Tyndale University College Faculty Association.'
url:              http://tucfa.ca
baseurl:          /tucfa.github.io/

author:
  name:           'FA Secretary-Treasurer'
  url:            http://danieldriver.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tucfa/tucfa.github.io
