# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tucfa.ca
tagline:          'Faculty Association of Tyndale University College, Toronto'
description:      'Official website of the Tyndale University College Faculty Association.'
url:              http://tucfa.ca
baseurl:          /

author:
  name:           'FA Secretary-Treasurer'
  url:            http://danieldriver.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tucfa/tucfa.github.io
